# Generated by Django 5.2.6 on 2026-08-24 08:26

import apps.careers.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'career benefit',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('department_ar', models.CharField(blank=True, max_length=120)),
                ('department_en', models.CharField(blank=True, max_length=120)),
                ('location_ar', models.CharField(blank=True, max_length=160)),
                ('location_en', models.CharField(blank=True, max_length=160)),
                ('employment_type_ar', models.CharField(blank=True, max_length=80)),
                ('employment_type_en', models.CharField(blank=True, max_length=80)),
                ('experience_ar', models.CharField(blank=True, max_length=120)),
                ('experience_en', models.CharField(blank=True, max_length=120)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('responsibilities_ar', models.TextField(blank=True, help_text='One item per line.')),
                ('responsibilities_en', models.TextField(blank=True, help_text='One item per line.')),
                ('requirements_ar', models.TextField(blank=True, help_text='One item per line.')),
                ('requirements_en', models.TextField(blank=True, help_text='One item per line.')),
                ('closes_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'job opening',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('years_experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('role_other', models.CharField(blank=True, help_text='Free-text role when the candidate applied without picking an opening.', max_length=200)),
                ('cv_link', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, upload_to=apps.careers.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('note', models.TextField(blank=True)),
                ('locale', models.CharField(default='ar', max_length=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Not proceeding')], db_index=True, default='new', max_length=16)),
                ('internal_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(blank=True, help_text='Blank for a general application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.jobopening')),
            ],
            options={
                'verbose_name': 'job application',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='careers_job_status_13e14c_idx')],
            },
        ),
    ]
