# Generated by Django 5.2.6 on 2026-08-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('key', models.SlugField(help_text="Filter key used by the frontend, e.g. 'water'. Must not be 'all'.", max_length=32, unique=True)),
                ('label_ar', models.CharField(blank=True, max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'project category',
                'verbose_name_plural': 'project categories',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('planned', 'Planned')], db_index=True, default='completed', max_length=16)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('location_ar', models.CharField(blank=True, max_length=160)),
                ('location_en', models.CharField(blank=True, max_length=160)),
                ('client_ar', models.CharField(blank=True, max_length=200)),
                ('client_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('scope_ar', models.TextField(blank=True, help_text='One scope item per line.')),
                ('scope_en', models.TextField(blank=True, help_text='One scope item per line.')),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('image_url', models.CharField(blank=True, help_text='Used when no image is uploaded.', max_length=500)),
                ('year_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'verbose_name': 'project',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
