# Generated by Django 5.2.6 on 2026-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('hero', 'Hero'), ('equipment', 'Equipment'), ('water', 'Water'), ('urban', 'Urban'), ('careers', 'Careers'), ('chairman', 'Chairman'), ('gm', 'General manager'), ('project', 'Project gallery')], db_index=True, max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='site/')),
                ('external_url', models.CharField(blank=True, help_text='Used when no file is uploaded — e.g. an existing CDN URL.', max_length=500)),
                ('alt_text_ar', models.CharField(blank=True, max_length=255)),
                ('alt_text_en', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('slot', 'order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('commercial_registration', models.CharField(blank=True, max_length=32, verbose_name='commercial registration (CR)')),
                ('brand_line_ar', models.CharField(blank=True, max_length=160)),
                ('brand_line_en', models.CharField(blank=True, max_length=160)),
                ('address_ar', models.CharField(blank=True, max_length=255)),
                ('address_en', models.CharField(blank=True, max_length=255)),
                ('tagline_ar', models.TextField(blank=True)),
                ('tagline_en', models.TextField(blank=True)),
                ('rights_ar', models.CharField(blank=True, max_length=255)),
                ('rights_en', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('logo_mark', models.ImageField(blank=True, upload_to='branding/')),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('logo_mark_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
