# Generated by Django 5.2.6 on 2026-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('title_ar', models.CharField(blank=True, max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('description_ar', models.CharField(blank=True, max_length=255)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/')),
            ],
            options={
                'verbose_name': 'ISO certification',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'core value',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'equipment feature',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_ar', models.CharField(blank=True, max_length=120)),
                ('badge_en', models.CharField(blank=True, max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('lead_ar', models.TextField(blank=True)),
                ('lead_en', models.TextField(blank=True)),
                ('cta_primary_ar', models.CharField(blank=True, max_length=120)),
                ('cta_primary_en', models.CharField(blank=True, max_length=120)),
                ('cta_secondary_ar', models.CharField(blank=True, max_length=120)),
                ('cta_secondary_en', models.CharField(blank=True, max_length=120)),
                ('scroll_hint_ar', models.CharField(blank=True, max_length=120)),
                ('scroll_hint_en', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'hero section',
                'verbose_name_plural': 'hero section',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('title_ar', models.CharField(blank=True, max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('bio_ar', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('expertise_ar', models.TextField(blank=True, help_text='One area of expertise per line.')),
                ('expertise_en', models.TextField(blank=True, help_text='One area of expertise per line.')),
                ('photo', models.ImageField(blank=True, upload_to='leadership/')),
                ('photo_url', models.CharField(blank=True, help_text='Used when no photo is uploaded.', max_length=500)),
            ],
            options={
                'verbose_name': 'leader',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('year_ar', models.CharField(blank=True, max_length=32)),
                ('year_en', models.CharField(blank=True, max_length=32)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'journey milestone',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('anchor', models.SlugField(help_text="Section id the link scrolls to, e.g. 'services'.", max_length=64, unique=True)),
                ('label_ar', models.CharField(blank=True, max_length=64)),
                ('label_en', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'navigation item',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('intro', 'About'), ('why', 'Why choose us'), ('services', 'Services'), ('projects', 'Projects'), ('equipment', 'Equipment'), ('certifications', 'Certifications'), ('journey', 'Journey'), ('leadership', 'Leadership'), ('contact', 'Contact'), ('careers', 'Careers'), ('footer', 'Footer')], max_length=32, unique=True)),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120)),
                ('eyebrow_en', models.CharField(blank=True, max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('lead_ar', models.TextField(blank=True)),
                ('lead_en', models.TextField(blank=True)),
                ('body_1_ar', models.TextField(blank=True, verbose_name='paragraph 1 (AR)')),
                ('body_1_en', models.TextField(blank=True, verbose_name='paragraph 1 (EN)')),
                ('body_2_ar', models.TextField(blank=True, verbose_name='paragraph 2 (AR)')),
                ('body_2_en', models.TextField(blank=True, verbose_name='paragraph 2 (EN)')),
                ('body_3_ar', models.TextField(blank=True, verbose_name='paragraph 3 (AR)')),
                ('body_3_en', models.TextField(blank=True, verbose_name='paragraph 3 (EN)')),
                ('callout_title_ar', models.CharField(blank=True, max_length=200)),
                ('callout_title_en', models.CharField(blank=True, max_length=200)),
                ('callout_body_ar', models.TextField(blank=True)),
                ('callout_body_en', models.TextField(blank=True)),
                ('list_heading_ar', models.CharField(blank=True, max_length=160)),
                ('list_heading_en', models.CharField(blank=True, max_length=160)),
                ('list_ar', models.TextField(blank=True, help_text='One item per line.')),
                ('list_en', models.TextField(blank=True, help_text='One item per line.')),
                ('cta_ar', models.CharField(blank=True, max_length=120)),
                ('cta_en', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name used by the frontend, e.g. 'Droplets'.", max_length=64)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('capabilities_ar', models.TextField(blank=True, help_text='One capability per line.')),
                ('capabilities_en', models.TextField(blank=True, help_text='One capability per line.')),
            ],
            options={
                'verbose_name': 'service',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('value', models.CharField(help_text="e.g. '2007', '150+', '100%'.", max_length=32)),
                ('label_ar', models.CharField(blank=True, max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'headline statistic',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
