# Generated by Django 5.2.6 on 2026-08-24 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first on the site.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this item from the public site without deleting it.')),
                ('key', models.SlugField(max_length=48, unique=True)),
                ('label_ar', models.CharField(blank=True, max_length=160)),
                ('label_en', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'project type',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('company', models.CharField(max_length=200)),
                ('project_type_other', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('locale', models.CharField(default='ar', max_length=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote sent'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], db_index=True, default='new', max_length=16)),
                ('internal_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='leads.projecttype')),
            ],
            options={
                'verbose_name': 'quote request',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_quote_status_be2968_idx')],
            },
        ),
    ]
