# Generated by Django 5.2.6 on 2026-08-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'contact message'},
        ),
    ]
