"""Write the site bundle back out as ``site-data.js``.

On a free host the web service sleeps when idle, so the first request after a
quiet period waits out a cold start. That is fine for submitting a form — the
visitor has just clicked a button and expects to wait a moment — but it is not
fine for painting the page.

So content stays a static file: edit in the admin, run this command, commit the
regenerated ``site-data.js``. The page loads instantly with no API call, and the
backend is only reached when someone actually submits something.

Output is byte-compatible with the file the site already loads — same
``window.SACC_SITE`` assignment, same keys — so nothing in the page changes.
"""
import json
from pathlib import Path

from django.core.management.base import BaseCommand

from apps.content.bundle import build_site_bundle

HEADER = """/* Generated by `manage.py export_site_data` — do not edit by hand.
   Content is maintained in the Django admin; re-run the command after a change
   and commit the result. */
"""


class Command(BaseCommand):
    help = "Export the current content as site-data.js for the static frontend."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            default=None,
            help="Where to write the file. Defaults to the site-data.js beside the page.",
        )
        parser.add_argument(
            "--json",
            action="store_true",
            help="Write plain JSON instead of the window.SACC_SITE assignment.",
        )
        parser.add_argument(
            "--check",
            action="store_true",
            help=(
                "Do not write; exit 1 if the file on disk differs from the database. "
                "Useful in CI to catch content edited in the admin but never exported."
            ),
        )

    def handle(self, *args, **options):
        bundle = build_site_bundle()

        if options["output"]:
            target = Path(options["output"])
        else:
            # backend/ -> repository root, where the page and its data file live.
            target = Path(__file__).resolve().parents[5] / "site-data.js"

        payload = json.dumps(bundle, ensure_ascii=False, indent=2)
        content = payload if options["json"] else f"{HEADER}window.SACC_SITE = {payload};\n"

        if options["check"]:
            self._check(target, content)
            return

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        size_kb = len(content.encode("utf-8")) / 1024
        self.stdout.write(
            self.style.SUCCESS(f"Wrote {target} ({size_kb:.0f} KB)")
        )

    def _check(self, target: Path, content: str):
        if not target.exists():
            self.stderr.write(self.style.ERROR(f"{target} does not exist."))
            raise SystemExit(1)
        if target.read_text(encoding="utf-8") == content:
            self.stdout.write(self.style.SUCCESS(f"{target} is up to date."))
            return
        self.stderr.write(
            self.style.ERROR(
                f"{target} is out of date — run `manage.py export_site_data` and commit it."
            )
        )
        raise SystemExit(1)
